# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3ad7066e7ebbe31e9eceb4ad8ef0f25e745f61e13b92760dac125f051d7de3c0fd18c31352eb816ebb98b320dcd035f6eaa76252a47a360c2b872e02ab8ab72

test:
  secret_key_base: 836f3b9a68384ce470c9cbc4d5b0270d24e0a8fff9f2252b758d5cf1131d3ab611bcf372d69d556eb9b991879bcfa490741cf0dd0b017082ca32fa523abc74fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
